### ISSUE TITLE
h5py and appveyor

### ISSUE THREAD

**Issue by aragilar** [h5py/h5py#791]
This is an issue to track progress on getting h5py to build on appveyor, and potentially build windows wheels on appveyor, as well as getting it to pass the tests on appveyor.

### Setting up appveyor
- [x] Create h5py appveyor account
- [x] Merge in appveyor config (#795)
- [x] Sort out wheel building/uploading to PyPI

### Fix windows issues
- [x] #779 (Fixed by #787)
- [x] #711 (Fixed by #793)
- [x] #699 (Not needed for appveyor, but needs to be sorted out for wheel)
- [x] #789 (no associated issue)
- [ ] #790 (no associated issue)
- [x] #794 (no associated issue)
- [x] #800 (no associated issue)

**Comment by andreabedini** [comment]
Pinging @tomkooij who's done similar work for PyTables.

**Comment by tomkooij** [comment]
No problem! 

@aragilar: Do you want me to contribute to your branch, once you have uploaded it? (If needed) or do you want me to port the pytables appveyor framework? I have various wheelbuilders, feel free to copy anything you need:

https://github.com/tomkooij/pytables-wheel-builder
https://github.com/tomkooij/pytables-wheels (MacPython/pytables-wheels)

I probably have some time this week, so let me know if I can contribute.

Related: It should now be possible to skip downloading miniconda on appveyor, might save about a minute runtime.

**Comment by aragilar** [comment]
Most of the work was in #758, which works (h5py builds, tests fail but that's because we're not testing on Windows 😉) but is a mess, I've been splitting it apart and cleaning it up. There's a probably few more bugs that need to be added to the list above, but that's nearly complete.

I didn't use conda as tox and conda don't mesh currently, and it means there's no chance of implicit conda dependence (and h5py doesn't depend on the harder-to-install-on-Windows parts of the ecosystem, e.g. Fortran, so I don't see any advantage to moving over to using conda for now).

There's a pre-existing wheel creation repo at https://github.com/MacPython/h5py-wheels (or https://github.com/matthew-brett/h5py-wheels, I'm not sure which one is the official one), that's was where I was going to add the actual wheel building/uploading. I don't know if the latest h5py release builds on windows, you could try porting the pytables-wheels frame to the h5py-wheels repo, though I don't know how successful that'd be (I haven't tried building the latest h5py release on Windows, and I lack ready access to any kind of Windows dev system, so I've been reliant on appveyor to do testing).

**Comment by tomkooij** [comment]
Yes, `tox` is a very different approach from `conda`, so my examples are of little help.

Building hdf5lib every single time from source does seem a pain... (But I guess there are no binaries for vc9/win32 and such...)

**Comment by andreabedini** [comment]
This should also address #785.

**Comment by andreabedini** [comment]
> There's a pre-existing wheel creation repo at https://github.com/MacPython/h5py-wheels (or https://github.com/matthew-brett/h5py-wheels, I'm not sure which one is the official one)

MacPython/h5py-wheels is the official one, the other is Matthew's personal branch.

@tomkooij I see that you merged some support for appveyor in Matthew's multibuild. Does that mean h5py can now build windows wheels for free? (turning on appveyor on MacPython/h5py-wheels)

**Comment by tomkooij** [comment]
@andreabedini : The appveyor/multibuild stuff relies on `conda`. This is used because it can be a real pain to build libraries from source on Windows, with each new version of MSVC++ there seem to be an new endless string of problems. As most of this is already fixed in 'anaconda' and 'conda-forge' it saves a lot of dev time. (Builds are much faster as well).

So h5py is not compatible with multibuild/appveyor (because of tox). But I'll have a look.

**Comment by aragilar** [comment]
Using tox isn't required, h5py-wheels currently just calls the test system. The main reason I've been using tox is it makes it easy to test a bunch of different configurations both locally and on travis (e.g. is our claimed minimum version actually supported?). I did see some discussion of adding conda support to tox, but I don't know what happened to it...

**Comment by tomkooij** [comment]
I've brewed up a simple appveyor 'build wheel, install from wheel and run tests' . I have only included the fix for #699. The rest is very straight forward, thanks to conda. The appveyor build is here: https://ci.appveyor.com/project/tomkooij/h5py/build/job/om5jyhjkrcpl7wn4

There are some failures from the tests, at least from the issues listed above. I'm not sure it's *only* related to the issues above, I'll have to check more carefully.

This can be (very) easily implemented in the wheelbuilder MacPython/h5py-wheels. I'll provide a PR if this is the way to go.

**Comment by aragilar** [comment]
@tomkooij Looks good, the TestFileImage test is failing because there's confusion between the version of HDF5 h5py thinks it's compiling against and the actual HDF5 version, this is fixed by specifying `HDF5_VERSION`.

**Comment by aragilar** [comment]
According to https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization, we need to have someone create a new appveyor account with an associated email. @tomkooij What did PyTables do about this? How is that new account managed?

**Comment by tomkooij** [comment]
Pytables uses an account "pytablesbot" on appveyor: https://ci.appveyor.com/project/PyTablesBot/pytables

I'm not sure who manages that account. I'm also not sure why one cannot use or link a GitHub organisation and give the Github organisation members access. 

The pytables solution is of no real help, I'm afraid.

**Comment by aragilar** [comment]
There's now h5py builds happening at https://ci.appveyor.com/project/h5py/h5py.
